Releases/v3
TriPSs/conventional-changelog-action pull request #225
Opened 2023-08-02 14:25 UTC by srdanrasic

2023-08-02 14:31 UTC, TriPSs requested changes
Funny that for the actions to generate a changelog based off conventional commits you did not use a single conventional commit, If I where to merge this it would not show up in the changelog.

Please answer/process the comments and commit them **with** a commit following the guidelines.

2023-08-02 14:31 UTC, TriPSs commented on action.yml
> -    default: "v"
This would be a breaking change, can you revert?

2023-08-02 14:31 UTC, TriPSs commented on action.yml
> +  breaking-bumps-minor:
Would this logic not be better placed in a preset?

2023-10-16 07:39 UTC, srdanrasic commented
Sorry @TriPSs, this was opened completely accidentally.

2023-10-16 07:39 UTC, closed without merging